### ISSUE TITLE
Tar error: File removed before we read it /bin/tar:

### ISSUE THREAD

**Issue by planetahuevo** [sebastianfeldmann/phpbu#114]
I have got this error using tar: 
File removed before we read it /bin/tar:
It was because I delete some files during the backup process but I was wondering why this happen if I already have the 

ignoreFailedRead  setup to true:
 <option name="ignoreFailedRead" value="true"/>

I found this link, but I am not sure is the same thing.
https://stackoverflow.com/questions/20318852/tar-file-changed-as-we-read-it
Any ideas?

**Comment by sebastianfeldmann** [comment]
When I understand the documentation correctly it is possible to suppress these warning via the `--warning` option.

But the exit code should still be `0`.
So the tar should be created anyway.

To not display this errors phpbu must use the `--warning` option.

**Comment by planetahuevo** [comment]
The problem is that I am getting an error. 
phpbu is marking it as failed.
Not sure why. Considering to sync into another folder and then use the tar... but that is an overkill...

**Comment by sebastianfeldmann** [comment]
Could you try to execute tar directly with this option

```
--warning='file-removed'
```

And check if that works, if so I would add this option to phpbu

**Comment by planetahuevo** [comment]
I will try, the problem is that is not failing all the time. I will try to remove a file manually to force the problem. 
Not sure when I can do the tests...

**Comment by planetahuevo** [comment]
Hi, 
I have not tested it yet but I got the error tonight: 
```
Exception 'RuntimeException' with message 'Command failed: exit-code: 1 message: /bin/tar: XXXXXXXX/XXXXXXX/xxxx.log: file changed as we read it ' in phar:///XXXXX/phpbu/lib/phpdotenv/Command/Runner/Simple.php:57
```

**Comment by sebastianfeldmann** [comment]
This is strange normally those warnings should not affect the exit code of `tar`
as stated [here](https://www.gnu.org/software/tar/manual/html_section/tar_27.html)

> Sometimes, while performing the requested task, GNU tar notices some conditions that are not exactly errors, but which the user should be aware of. When this happens, tar issues a warning message describing the condition. Warning messages are output to the standard error and they do not affect the exit code of tar command. 

Some of those warnings are:
- file changed as we read it
- File removed before we read it

And more

I will try to reproduce this locally

**Comment by planetahuevo** [comment]
From the link I posted: 
"Still the exit code return by the tar is "1" in warning message case: http://www.gnu.org/software/tar/manual/html_section/Synopsis.html"

**Comment by sebastianfeldmann** [comment]
Maybe phpbu should accept exit code 1 as well if the `ignoreFailedRead` option is set

**Comment by sebastianfeldmann** [comment]
I've just released version 5.0.5 with a fix that allows the `tar` command to exit with return code 1 as well if the `ignoreFailedRead` option is set

I hope that fixes your problem ;)

**Comment by sebastianfeldmann** [comment]
Please let me know if it works
Cheers, Sebastian

**Comment by planetahuevo** [comment]
I will try it and let you know. 

Thank you!!

**Comment by planetahuevo** [comment]
Hi, testing it right now and got this error, so it seems it is still failing with exit=1: 
"
phpbu --configuration=phpbu.xml
phpbu 5.0.5 by Sebastian Feldmann and contributors.

Time: 4.03 minutes, Memory: 10.00MB

Exception 'RuntimeException' with message 'Command failed:
  exit-code: 1
  message:   /bin/tar: public: file changed as we read it

'
in phar:///usr/local/bin/phpbu/lib/phpdotenv/Command/Runner/Simple.php:57

FAILURE!
Backups: 2, failed Checks: 0, failed Crypts: 0, failed Syncs: 0, failed Clea: 0.
"

**Comment by planetahuevo** [comment]
My config file has this option: 
<option name="ignoreFailedRead" value="true"/>

**Comment by planetahuevo** [comment]
`<option name="ignoreFailedRead" value="true"/>`

**Comment by sebastianfeldmann** [comment]
Ok I see the proablem now.
The exception is thrown way before phpbu tries to handle the exit codes.
I will release ASAP

**Comment by planetahuevo** [comment]
No hurries! It does work most of the time. :)

**Comment by sebastianfeldmann** [comment]
So I upgraded the `Commands` so you can define some `acceptableExitCodes`.
By default this is only `0`
So if the `ignoreFailedRead` option is set, the `tar` command has two acceptable exit codes `0` and `1` so hopefully no exception will be thrown anymore ;)

So now this should work, if not I'm going to shoot myself 😜

Please update to the latest version `5.0.6` and have a try #fingersCrossed 🙈

**Comment by planetahuevo** [comment]
I will be traveling a lot next month, so I won´t be able to test it properly until I am back. 
I am sure you got it, and if not, it is not a big deal. 
Thank you for the great work.

**Comment by sebastianfeldmann** [comment]
No worries
Don’t hesitate to let me know if it doesn’t work.
Thanks for your patience and your support/feedback to make phpbu better.

**Comment by sebastianfeldmann** [comment]
I'll close this issue, if you still have problems feel free to reopen it

**Comment by planetahuevo** [comment]
Yeah, sorry I didn´t wrote you back. I think it is fixed. 

Thanks!
